def fill_up_alpha_cdr3(cdr3: str, j_gene: str):
    TRAJ_SEQUENCE = {
        'TRAJ1': 'YESITSQLQFGKGTRVSTSP',
        'TRAJ2': 'NTGGTIDKLTFGKGTHVFIIS',
        'TRAJ3': 'GYSSASKIIFGSGTRLSIRP',
        'TRAJ4': 'FSGGYNKLIFGAGTRLAVHP',
        'TRAJ5': 'DTGRRALTFGSGTRLQVQP',
        'TRAJ6': 'ASGGSYIPTFGRGTSLIVHP',
        'TRAJ7': 'DYGNNRLAFGKGNQVVVIP',
        'TRAJ8': 'NTGFQKLVFGTGTRLLVSP',
        'TRAJ9': 'GNTGGFKTIFGAGTRLFVKA',
        'TRAJ10': 'ILTGGGNKLTFGTGTQLKVEL',
        'TRAJ11': 'NSGYSTLTFGKGTMLLVSP',
        'TRAJ12': 'MDSSYKLIFGSGTRLLVRP',
        'TRAJ13': 'NSGGYQKVTFGIGTKLQVIP',
        'TRAJ14': 'IYSTFIFGSGTRLSVKP',
        'TRAJ15': 'NQAGTALIFGKGTTLSVSS',
        'TRAJ16': 'FSDGQKLLFARGTMLKVDL',
        'TRAJ17': 'IKAAGNKLTFGGGTRVLVKP',
        'TRAJ18': 'DRGSTLGRLYFGRGTQLTVWP',
        'TRAJ19': 'YQRFYNFTFGKGSKHNVTP',
        'TRAJ20': 'SNDYKLSFGAGTTVTVRA',
        'TRAJ21': 'YNFNKFYFGSGTKLNVKP',
        'TRAJ22': 'SSGSARQLTFGSGTQLTVLP',
        'TRAJ23': 'IYNQGGKLIFGQGTELSVKP',
        'TRAJ24': 'TTDSWGKFEFGAGTQVVVTP',
        'TRAJ25': 'EGQGFSFIFGKGTRLLVKP',
        'TRAJ26': 'DNYGQNFVFGPGTRLSVLP',
        'TRAJ27': 'NTNAGKSTFGDGTTLTVKP',
        'TRAJ28': 'YSGAGSYQLTFGKGTKLSVIP',
        'TRAJ29': 'NSGNTPLVFGKGTRLSVIA',
        'TRAJ30': 'NRDDKIIFGKGTRLHILP',
        'TRAJ31': 'NNNARLMFGDGTQLVVKP',
        'TRAJ32': 'NYGGATNKLIFGTGTLLAVQP',
        'TRAJ33': 'DSNYQLIWGAGTKLIIKP',
        'TRAJ34': 'SYNTDKLIFGTGTRLQVFP',
        'TRAJ35': 'IGFGNVLHCGSGTQVIVLP',
        'TRAJ36': 'QTGANNLFFGTGTRLTVIP',
        'TRAJ37': 'GSGNTGKLIFGQGTTLQVKP',
        'TRAJ38': 'NAGNNRKLIWGLGTSLAVNP',
        'TRAJ39': 'NNNAGNMLTFGGGTRLMVKP',
        'TRAJ40': 'TTSGTYKYIFGTGTRLKVLA',
        'TRAJ41': 'NSNSGYALNFGKGTSLLVTP',
        'TRAJ42': 'NYGGSQGNLIFGKGTKLSVKP',
        'TRAJ43': 'NNNDMRFGAGTRLTVKP',
        'TRAJ44': 'NTGTASKLTFGTGTRLQVTL',
        'TRAJ45': 'YSGGGADGLTFGKGTHLIIQP',
        'TRAJ46': 'KKSSGDKLTFGTGTRLAVRP',
        'TRAJ47': 'EYGNKLVFGAGTILRVKS',
        'TRAJ48': 'SNFGNEKLTFGTGTRLTIIP',
        'TRAJ49': 'NTGNQFYFGTGTSLTVIP',
        'TRAJ50': 'KTSYDKVIFGPGTSLSVIP',
        'TRAJ51': 'MRDSYEKLIFGKET*LTVKP',
        'TRAJ52': 'NAGGTSYGKLTFGQGTILTVHP',
        'TRAJ53': 'NSGGSNYKLTFGKGTLLTVNP',
        'TRAJ54': 'IQGAQKLVFGQGTRLTINP',
        'TRAJ55': 'KCW*CSCWGKGMSTKINP',
        'TRAJ56': 'YTGANSKLTFGKGITLSVRP',
        'TRAJ57': 'TQGGSEKLVFGKGTKLTVNP',
        'TRAJ58': 'ETSGSRLTFGEGTQLTVNP',
        'TRAJ59': 'KEGNRKFTFGMGTQVRVKL',
        'TRAJ60': 'KIT*MLNFGKGTELIVSL',
        'TRAJ61': 'YRVNRKLTFGANTRGIMKL',
    }
    if j_gene not in TRAJ_SEQUENCE:
        return cdr3
    sequence_1 = TRAJ_SEQUENCE[j_gene]
    sequence_2 = cdr3
    overlap = ''
    for n in range(len(sequence_1)):
        for i in range(1,n):
            if sequence_2.endswith(sequence_1[i:n+1]):
                overlap = sequence_1[i-1:n+1]
    if not overlap:
        return cdr3
    return sequence_2 + sequence_1[sequence_1.index(overlap)+len(overlap):sequence_1.index("F")+1]


